kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "zfs-feature-discovery.configMap.zfsbin.name" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  host-zfs: |
    {{- include "zfs-feature-discovery.hostBinWrapperScript" (dict "hostBin" .Values.zfsDiscovery.zfs.hostBin "name" "zfs") | nindent 4}}
  host-zpool: |
    {{- include "zfs-feature-discovery.hostBinWrapperScript" (dict "hostBin" .Values.zfsDiscovery.zpool.hostBin "name" "zpool") | nindent 4}}
  host-hostid: |
    {{- include "zfs-feature-discovery.hostBinWrapperScript" (dict "hostBin" .Values.zfsDiscovery.hostid.hostBin "name" "hostid") | nindent 4}}

