name: lint
on:
  pull_request:
    types:
      - synchronize
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Pre-commit
        uses: cloudposse/github-action-pre-commit@v2.1.2
