name: tag-release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GH_RELEASE_TOKEN }}"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install hatch
        run: pip install hatch pyyaml

      - name: Tag release
        run: |
          .github/release.py tag-release

      - name: Tag helm releases
        run: |
          .github/release.py tag-helm-releases
