name: tag-helm-releases

on:
  push:
    branches:
      - main
    paths:
      - deployments/helm/zfs-feature-discovery/Chart.yaml

jobs:
  tag-helm-releases:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install hatch
        run: pip install hatch

      - name: Tag new version
        run: .github/release.py tag-helm-releases
